### ISSUE TITLE
Apply instruction how to use task plugin

### ISSUE THREAD

**Issue by AndrienkoAleksandr** [eclipse/che-theia-task-plugin#11]
Apply instruction how to use task plugin: how to create new Theia task, how run them and so on.

**Comment by azatsarynnyy** [comment]
fixed by https://github.com/eclipse/che-theia-task-plugin/pull/16
The readme file has been updated with the steps how to run/develop Che Task extension.

> how to create new Theia task, how run them and so on

this plugin doesn't change the general mechanism of working with the Theia Tasks. The related instructions can be found in [upstream repo](https://github.com/theia-ide/theia/tree/master/packages/task)
